//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleConcurrency.DataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM XUsers WHERE IsDeleted = 0")]
        public string GetAllXUsersCmd {
            get {
                return ((string)(this["GetAllXUsersCmd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM YUsers WHERE IsDeleted = 0")]
        public string GetAllYUsersCmd {
            get {
                return ((string)(this["GetAllYUsersCmd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GetYUserForEditing")]
        public string GetYUserForEditingSPName {
            get {
                return ((string)(this["GetYUserForEditingSPName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into YUsers (FirstName, LastName) values(@FirstName, @LastName); SELECT SC" +
            "OPE_IDENTITY()")]
        public string AddYUserCmd {
            get {
                return ((string)(this["AddYUserCmd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("insert into XUsers (FirstName, LastName, IsDeleted, UpdateDate) values(@FirstName" +
            ", @LastName, @IsDeleted, @UpdateDate); SELECT SCOPE_IDENTITY()")]
        public string AddXUserCmd {
            get {
                return ((string)(this["AddXUserCmd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeleteXUser")]
        public string DeleteXUserSpName {
            get {
                return ((string)(this["DeleteXUserSpName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeleteYUser")]
        public string DeleteYUserSPName {
            get {
                return ((string)(this["DeleteYUserSPName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpdateXUser")]
        public string UpdateXUserSPName {
            get {
                return ((string)(this["UpdateXUserSPName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UpdateYUser")]
        public string UpdateYUserSPName {
            get {
                return ((string)(this["UpdateYUserSPName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReleaseYUser")]
        public string ReleaseYUserSPName {
            get {
                return ((string)(this["ReleaseYUserSPName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM XUsers WHERE Id=@Id AND IsDeleted = 0")]
        public string GetXUserCmd {
            get {
                return ((string)(this["GetXUserCmd"]));
            }
        }
    }
}
